# This file was auto-generated by Fern from our API Definition.

import typing

import httpx

from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.chat.client import AsyncChatClient, ChatClient
from .resources.copilot.client import AsyncCopilotClient, CopilotClient


class OpenCopilotApi:
    def __init__(self, *, base_url: str, timeout: typing.Optional[float] = 60):
        self._client_wrapper = SyncClientWrapper(base_url=base_url, httpx_client=httpx.Client(timeout=timeout))
        self.chat = ChatClient(client_wrapper=self._client_wrapper)
        self.copilot = CopilotClient(client_wrapper=self._client_wrapper)


class AsyncOpenCopilotApi:
    def __init__(self, *, base_url: str, timeout: typing.Optional[float] = 60):
        self._client_wrapper = AsyncClientWrapper(base_url=base_url, httpx_client=httpx.AsyncClient(timeout=timeout))
        self.chat = AsyncChatClient(client_wrapper=self._client_wrapper)
        self.copilot = AsyncCopilotClient(client_wrapper=self._client_wrapper)
